=== AlbertoArroyoS/LenguajesActividad2Alberto/Separados/Pruebas/V1/XSD/XSD_libros.xsd
<?xml version="1.0"?>
<!-- Este ejemplo es muy parecido a la validación de la Pelicula por DTD. Se ha quitado alguna
validación complicadas para hacer el ejemplo lo más sencillo posible-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Esquema que marca la estructura de un libro
        </xs:documentation>
    </xs:annotation>
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"></xs:element>
                <xs:element name="capitulo">
                    <xs:complexType>
                        <simpleContent>
                            <extension base="string">
                                <attribute name="pagina"></attribute>
                            </extension>
                        </simpleContent>
                        <xs:sequence>
                            <xs:element name="titulo_capitulo" type="xs:string"></xs:element>
                            <xs:element name="contenido"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="indice" type="xs:string"></xs:element>
                <xs:element name="sinopsis" type="xs:string"></xs:element>
            </xs:sequence>
        <!-- Podemos hacer los atributos obligatorios -->        
            <!-- Podemos hacer los atributos obligatorios -->
            <attribute name="id" type="string" use="required"></attribute>  
            <attribute name="tipo_clase" type="integer" use="required"></attribute>  
            <attribute name="paginas" type="integer" use="required"></attribute>  

        
        
        </xs:complexType>
    </xs:element>

</xs:schema>

=== AlbertoArroyoS/LenguajesActividad2Alberto/librosXSD.xml
<libro id="001" tipo_clase="didáctico" paginas="250" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation= "XSD/XSD_libros.xsd">
    <titulo>Programación orientada a objetos con Java</titulo>
    <capitulo paginas="10">
        <titulo_capitulo>Introducción a la programación orientada a objetos</titulo_capitulo>
        <contenido>En este capítulo se presenta el paradigma de programación orientada a objetos y se introducen los conceptos básicos necesarios para entender su funcionamiento.</contenido>
    </capitulo>
    <capitulo paginas="20">
        <titulo_capitulo>Clases y objetos en Java</titulo_capitulo>
        <contenido>En este capítulo se explica cómo definir clases y objetos en Java, y cómo crear instancias de objetos.</contenido>
    </capitulo>
    <indice>Índice</indice>
    <sinopsis>Este libro es una introducción a la programación orientada a objetos con Java, dirigido a estudiantes y desarrolladores principiantes.</sinopsis>
</libro>
