=== AlbertoArroyoS/LenguajesActividad2Alberto/DTD_libros.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro (id,tipo_clase,paginas)>

<!-- Definimos los atributos del libro -->
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didÃ¡ctico) #REQUIRED>
<!ATTLIST libro paginas CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>

<!ELEMENT capitulo (c_paginas)>
<!ATTLIST capitulo c_paginas CDATA >

<!ELEMENT titulo_capitulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido enlace CDATA #REQUIRED>

<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!-- <!ENTITY entity name SYSTEM "URI/URL"> -->

=== AlbertoArroyoS/LenguajesActividad2Alberto/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "DTD_libros.dtd">
 <!--  Libros    -->
<libros>
    <libro id="L1234" tipo_clase="didáctico" paginas="150">
        <titulo></titulo>
        <capitulo c_paginas="20">
            <titulo_capitulo> </titulo_capitulo>
            <contenido enlace="enlace a la información"></contenido>
        </capitulo>
        <indice></indice>
        <sinopsis></sinopsis>
    </libro>
</libros>
